### ISSUE TITLE
CORS request error when attempting to follow stroop example

### ISSUE THREAD

**Issue by belledon** [FelixHenninger/lab.js#58]
### What would you like or expect to see?

I am a new user that would like to adapt the stroop code-based example.

When opening the example's `index.html` (`tasks/Stroop (code-based)/index.html`) I expected the experiment to load to the intro

### What is currently happening?

Every request for content in `pages` results in a cannot fetch error:
```
URL scheme must be "http" or "https" for CORS request.
(anonymous) @ html.js:21
html.js:26 Error while loading content:  TypeError: Failed to fetch
    at html.js:21
    at async Screen.value (eventAPI.js:153)
    at async Screen.value (core.js:377)
    at async Promise.all (index 1)
    at async Sequence.value (flow.js:55)
    at async Sequence.value (eventAPI.js:153)
    at async Sequence.value (core.js:448)
    at async Sequence.value (core.js:490)
```

### Please describe the steps needed to reproduce this phenomenon

I replicated this by both using the `lib` from the latest [release](https://github.com/FelixHenninger/lab.js/releases/tag/v19.1.0) and building master. 

Also when starting from the minimal example in the starter kit,  screen objects such as 

```js
      new lab.html.Screen({
          content: 'Hello world!'
      }),
```

are fine, but objects with content such as:

```js
      new lab.html.Screen({
          contentUrl: 'pages/1-welcome.html',
          responses: {
              'keypress(Space)': 'continue'
          },
      }),
```
result with a cors  error

### Finally, please tell us which browser you're using (and the version thereof)

Tested on firefox `68.0.1 (64-bit)` and brave `0.67.119 Chromium: 76.0.3809.72 (Official Build) unknown (64-bit)`

Apologies if I'm missing something.

**Comment by FelixHenninger** [comment]
Hi @belledon, and thanks for checking out `lab.js`! (kudos especially for going the hardcore route through the code! 😍)

I think what you're encountering is a technical issue related to the browsers rather than the library itself: Recent browsers don't allow scripts to load content from the hard drive, and thus block `fetch` requests that use the `file://` protocol (as opposed to `http` and `https`).

I can replicate your findings, and also get the same code to work on a local webserver -- so my recommendation would probably be to setup a small local webserver and use that for development. (in the meantime, I should document how to run the code-based example).

Does that make sense? If you like, please be very warmly invited to hop over to our [community support chat](https://lab.js.org/resources/support/), I'd be thrilled to help you set up a local server, and also answer any further questions you have (ideas and suggestions are of course also welcome). Also feel free to discuss things within this issue, I'll do my best to keep an eye on it.

Kind regards, and thanks again,


-Felix

**Comment by belledon** [comment]
hi @FelixHenninger ,
Thanks for the quick reply and sorry for keeping this issue open over the weekend!

I think I understand a little more given your explanation!

I was able to get things running using [http-server](https://www.npmjs.com/package/http-server) to do a simple local run

**Comment by FelixHenninger** [comment]
Hej @belledon,

I'm super-glad to hear that things worked out for you! Don't worry about the issue, I'm always glad to help, and this wasn't hard 🙂. If you like, do stop by our [community support channel](https://lab.js.org/resources/support/), I'd be glad to help you and answer any other questions you have.

Here's one more thing I forgot to mention eariler: If you'd like to develop locally, you can always use the `content` option on an `html.Screen` to input `HTML` directly rather than loading it from an external file. The tradeoff with that, however, is slightly more verbose code overall -- it might be worth it if developing with a local server is a hassle for you.

Kind regards, happy experimenting, and all the best,


-Felix
