### ISSUE TITLE
Nested template parameter access not supported

### ISSUE THREAD

**Issue by nishkakar** [FelixHenninger/lab.js#84]
Here's a simplified example to showcase the problem.
```
const experiment = new lab.flow.Sequence({
  content: [
    new lab.flow.Loop({
      template: new lab.html.Screen({
        content: '${parameters.userPrompt}',
        parameters: {
          userPrompt: 'Hello ${parameters.user}',
        },
      }),
      templateParameters: [{ user: 1 }, { user: 2 }, { user: 3 }, { user: 4 }],
    }),
  ],
});
```
This snippet displays `Hello ${parameters.user}` instead of `Hello 1`.  We've come across this use case a few times now, so it would be nice if we can find a way to support this.

This seems to be related to #83, in that the `templateParameters` only become available in the `onPrepare` step instead of the constructor. Thanks for the help in advance!

**Comment by FelixHenninger** [comment]
Hi @nishkakar, and thanks for creating an issue around this! As I mentioned in the support, I'm not sure this will ever work because it creates potentially infinite cross-dependencies among parameters. I'm not sure that's something that is at all possible to resolve (always open for ideas, though!).

> This seems to be related to #83, in that the templateParameters only become available in the onPrepare step instead of the constructor. Thanks for the help in advance!

I discussed this briefly with @jdpigeon a few days back -- this is again something I'm not sure is possible because the `template` is initialized without knowing anything about the context it's running in (by necessity, barring some kind of lazy initialization). The `prepare` stage signals that the component is fully embedded in the study and all environment data is available -- could you re-write your code to use that instead?

Ok, so much real quick -- I hope this helps, would be happy to discuss library internals if that would help, but right now I'm out of ideas :-/

**Comment by nishkakar** [comment]
Thanks for the quick response @FelixHenninger. We'll investigate some work arounds.

**Comment by FelixHenninger** [comment]
👍 Happy to take a look at your code with you, if that's an option. I'm almost certain that there is another solution to this!
