### ISSUE TITLE
Data transmission template & Microsoft Edge

### ISSUE THREAD

**Issue by danheck** [FelixHenninger/lab.js#87]
When adding the data transmission template (beta) to the study, the study cannot be started when running Microsoft Edge (Firefox and Opera are okay). The browser gets stuck while showing: "The experiment is loading".

The website https://jshint.com/ indicates the following issues with the JavaScript code exported for the php backend, which could be relevant:

```
'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').
'Trailing comma in arguments lists' is only available in ES8 (use 'esversion: 8').
```

PS: This is not very urgent, since the data are stored incrementally anyways.

**Comment by FelixHenninger** [comment]
Hi @danheck, and many thanks for your report! Hope you find `lab.js` useful 🙂.

I'd be glad to take a closer look at this -- could you specify the version of Edge you've been testing on? I agree that the arrow function syntax is likely to be the issue here, but that has been [supported since Edge version 12](https://caniuse.com/#feat=arrow-functions), as are [trailing commas](https://caniuse.com/#feat=mdn-javascript_functions_arrow_functions_trailing_comma).

Happy experimenting!


-Felix

**Comment by danheck** [comment]
Thanks, this was indeed an issue with a really old version of Edge:
Microsoft Edge 44.18362.449.0
whereas the current version is:
Version 83.0.478.58

Thanks for developing lab.js, we just finished data collection for our first study.
Daniel

**Comment by FelixHenninger** [comment]
Thanks for your feedback @danheck , glad that you're using `lab.js` in production! (and would be thrilled to hear how it's working for you). Just to be sure, did I catch you correctly that things are working in a recent Edge version? (which wouldn't be surprising given that the latest versions are Chrome under the hood, but I'd like to be sure)

Best, -Felix

**Comment by danheck** [comment]
I just tested this in the experiment builder in Edge, and adding the data transmission plugin does not cause an error anymore.

Data collection seemed to work very well. The biggest hurdle was to set up everything on a php server. The study is still online under this link: https://survey.online.uni-marburg.de/studies/movies/
