### ISSUE TITLE
Loop and Images (media)

### ISSUE THREAD

**Issue by RickyThoiry** [FelixHenninger/lab.js#92]
Hi Folks,

I please have a question.
I would like to create an experiment and make my screen loop with each time a different image.
In the online tutorial, it is shown how to loop a word and the color of the word with ${parameters.word} in the stimulus page and a column word in the loop page. but i do not know how to make an image vary at each loop. 
When I add an image, it is referenced as ${ this.files["XXX.bmp"] }
So I tried to change it to ${ this.files["${parameters.word}.bmp"] } in the stimulus page, under the "word" column I inscribed the name of the picture but it did not work .
I hope I was clear enough.
Someone would please help me?
Thank you very much
Kindest regard.
Ricky

**Comment by FelixHenninger** [comment]
Hi @RickyThoiry , and many thanks for your message! Please be very warmly invited to hop over to our [support channel](https://lab.js.org/resources/support/) where there's many more folks around to help.

As for your question, I think what's causing the issue is the nested placeholders (the `${}`). Everything inside of a placeholder counts as JavaScript code, and the `${}` only works in JS in [very specific conditions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). I think you have two options to try: First, you could write `${ this.files[this.parameters.word + ".bmp"] }`, or alternatively using the template literals in JS (note the backticks!): 
```
${ this.files[`${ this.parameters.word }.bmp`] }
```

Ok, so much real quick, I hope that helps you get started -- please do join the support channel for further information, we focus on technical issues here in the repository.

Happy experimenting!


-Felix

**Comment by RickyThoiry** [comment]
Hi Felix !
Thank you so much !
It works perfectly !
:)))
Great, I am very happy, again thank you very much !
Could I ask you if there is any way to install a timer (to measure the time taken by the student to answer each question or a timer for the whole activity) ?
Thank you very much Felix

**Comment by FelixHenninger** [comment]
Hi @RickyThoiry, sure thing! I'm not sure what you're looking for w/r/t the timer -- response durations will always be available in the `duration` column of the data, maybe that might be a place to look? For larger parts of the study (e.g. loops and sequences), the duration will reflect the complete time that part of the study was active.

Ok, hope that helps, and again please be very warmly invited to [join the support channel](https://lab.js.org/resources/support/), which is a far better place for these discussions :-) Best,


-Felix

**Comment by RickyThoiry** [comment]
Thank you very much Felix.
Yes I am immediatly going to take a look at the support channel.
And yes, exactly, for that last question I was looking for a way to measure the response durations.
I cannot find a duration column of the data.
Is it something I should add to the numerical parameter of my loop, or something in the content of the stimulus page?
Thanks Felix that was my last question :)
For the next ones I'll publish on the support channel

![duration1](https://user-images.githubusercontent.com/67922813/86633858-75952480-bfd1-11ea-82ba-ea734e8ba3dc.jpg)
![duration2](https://user-images.githubusercontent.com/67922813/86633866-78901500-bfd1-11ea-98ac-a666d8c5cf02.jpg)

**Comment by FelixHenninger** [comment]
Hej @RickyThoiry , you'll need to run the study to see the data that's being collected, I think you're all good otherwise. Please check out the [associated video tutorial](https://labjs.readthedocs.io/en/latest/learn/builder/4-data.html) for more in-depth information.

> For the next ones I'll publish on the support channel
That would be awesome! You'll also see that our super-kind community has answered many common questions already :-)

Happy experimenting!

-Felix

**Comment by RickyThoiry** [comment]
Thank you very much Felix for your kindness and wour help.

**Comment by FelixHenninger** [comment]
My pleasure, always happy to assist when I can 🙂 Take care, and see you over in the support channel! -F
